import type { IconColorKey } from "./colors";

interface IconDef {
  color: IconColorKey;
  glyph: string;
}

const FILE_ICONS: Record<string, IconDef> = {
  aac: { color: "red", glyph: "\u{e638}" },
  awk: { color: "orange", glyph: "\u{ebca}" },
  bash: { color: "orange", glyph: "\u{ebca}" },
  bat: { color: "orange", glyph: "\u{ebca}" },
  bmp: { color: "aqua", glyph: "\u{f1c5}" },
  c: { color: "blue", glyph: "\u{e61e}" },
  cc: { color: "blue", glyph: "\u{e61d}" },
  cfg: { color: "blue", glyph: "\u{e6b2}" },
  cjs: { color: "yellow", glyph: "\u{e781}" },
  clj: { color: "green", glyph: "\u{e768}" },
  cljc: { color: "green", glyph: "\u{e768}" },
  cljs: { color: "green", glyph: "\u{e768}" },
  cmake: { color: "blue", glyph: "\u{f15b}" },
  coffee: { color: "blue", glyph: "\u{e751}" },
  conf: { color: "blue", glyph: "\u{e6b2}" },
  cpp: { color: "blue", glyph: "\u{e61d}" },
  cs: { color: "blue", glyph: "\u{e7b2}" },
  csh: { color: "orange", glyph: "\u{ebca}" },
  css: { color: "blue", glyph: "\u{e749}" },
  cts: { color: "blue", glyph: "\u{e8ca}" },
  cxx: { color: "blue", glyph: "\u{e61d}" },
  dart: { color: "blue", glyph: "\u{e798}" },
  db: { color: "yellow", glyph: "\u{e7c4}" },
  dtd: { color: "green", glyph: "\u{e619}" },
  edn: { color: "green", glyph: "\u{e768}" },
  env: { color: "yellow", glyph: "\u{e615}" },
  ex: { color: "purple", glyph: "\u{e7cd}" },
  exs: { color: "purple", glyph: "\u{e7cd}" },
  fish: { color: "orange", glyph: "\u{ebca}" },
  flac: { color: "red", glyph: "\u{e638}" },
  fs: { color: "blue", glyph: "\u{e7a7}" },
  fsx: { color: "blue", glyph: "\u{e7a7}" },
  gemspec: { color: "red", glyph: "\u{e739}" },
  gif: { color: "aqua", glyph: "\u{f1c5}" },
  go: { color: "blue", glyph: "\u{e724}" },
  graphql: { color: "purple", glyph: "\u{e7f4}" },
  graphqls: { color: "purple", glyph: "\u{e7f4}" },
  gz: { color: "yellow", glyph: "\u{e6aa}" },
  h: { color: "blue", glyph: "\u{e61e}" },
  heic: { color: "aqua", glyph: "\u{f1c5}" },
  hh: { color: "blue", glyph: "\u{e61d}" },
  hpp: { color: "blue", glyph: "\u{e61d}" },
  hs: { color: "red", glyph: "\u{e777}" },
  htm: { color: "red", glyph: "\u{e736}" },
  html: { color: "red", glyph: "\u{e736}" },
  ico: { color: "aqua", glyph: "\u{f1c5}" },
  ini: { color: "blue", glyph: "\u{e6b2}" },
  java: { color: "red", glyph: "\u{e738}" },
  jpeg: { color: "aqua", glyph: "\u{f1c5}" },
  jpg: { color: "aqua", glyph: "\u{f1c5}" },
  js: { color: "yellow", glyph: "\u{e781}" },
  json: { color: "yellow", glyph: "\u{eb0f}" },
  json5: { color: "yellow", glyph: "\u{eb0f}" },
  jsonc: { color: "yellow", glyph: "\u{eb0f}" },
  jsx: { color: "yellow", glyph: "\u{e7ba}" },
  ksh: { color: "orange", glyph: "\u{ebca}" },
  kt: { color: "blue", glyph: "\u{e81b}" },
  kts: { color: "blue", glyph: "\u{e81b}" },
  lhs: { color: "red", glyph: "\u{e777}" },
  litcoffee: { color: "blue", glyph: "\u{e751}" },
  lock: { color: "yellow", glyph: "\u{f023}" },
  log: { color: "gray", glyph: "\u{f15b}" },
  lua: { color: "blue", glyph: "\u{e826}" },
  m4a: { color: "red", glyph: "\u{e638}" },
  makefile: { color: "red", glyph: "\u{e673}" },
  markdown: { color: "blue", glyph: "\u{e73e}" },
  md: { color: "blue", glyph: "\u{e73e}" },
  mdx: { color: "blue", glyph: "\u{e73e}" },
  mjs: { color: "yellow", glyph: "\u{e781}" },
  mp3: { color: "red", glyph: "\u{e638}" },
  mts: { color: "blue", glyph: "\u{e8ca}" },
  nim: { color: "yellow", glyph: "\u{e841}" },
  ogg: { color: "red", glyph: "\u{e638}" },
  otf: { color: "red", glyph: "\u{f15b}" },
  pdf: { color: "red", glyph: "\u{f1c1}" },
  php: { color: "blue", glyph: "\u{e73d}" },
  pl: { color: "purple", glyph: "\u{e769}" },
  plist: { color: "green", glyph: "\u{e619}" },
  pm: { color: "purple", glyph: "\u{e769}" },
  png: { color: "aqua", glyph: "\u{f1c5}" },
  properties: { color: "blue", glyph: "\u{e6b2}" },
  ps1: { color: "orange", glyph: "\u{e86c}" },
  psd1: { color: "orange", glyph: "\u{e86c}" },
  psm1: { color: "orange", glyph: "\u{e86c}" },
  py: { color: "blue", glyph: "\u{e73c}" },
  pyi: { color: "blue", glyph: "\u{e73c}" },
  pyw: { color: "blue", glyph: "\u{e73c}" },
  r: { color: "blue", glyph: "\u{e881}" },
  rb: { color: "red", glyph: "\u{e739}" },
  rs: { color: "orange", glyph: "\u{e7a8}" },
  rst: { color: "blue", glyph: "\u{e73e}" },
  sass: { color: "purple", glyph: "\u{e74b}" },
  sc: { color: "red", glyph: "\u{e737}" },
  scala: { color: "red", glyph: "\u{e737}" },
  scss: { color: "purple", glyph: "\u{e74b}" },
  sh: { color: "orange", glyph: "\u{ebca}" },
  sql: { color: "yellow", glyph: "\u{e7c4}" },
  sqlite: { color: "yellow", glyph: "\u{e7c4}" },
  sqlite3: { color: "yellow", glyph: "\u{e7c4}" },
  svelte: { color: "orange", glyph: "\u{e8b7}" },
  svg: { color: "aqua", glyph: "\u{f1c5}" },
  swift: { color: "orange", glyph: "\u{e755}" },
  tar: { color: "yellow", glyph: "\u{e6aa}" },
  tcsh: { color: "orange", glyph: "\u{ebca}" },
  tif: { color: "aqua", glyph: "\u{f1c5}" },
  tiff: { color: "aqua", glyph: "\u{f1c5}" },
  toml: { color: "blue", glyph: "\u{e6b2}" },
  ts: { color: "blue", glyph: "\u{e8ca}" },
  tsbuildinfo: { color: "yellow", glyph: "\u{eb0f}" },
  tsx: { color: "blue", glyph: "\u{e7ba}" },
  ttf: { color: "red", glyph: "\u{f15b}" },
  txt: { color: "gray", glyph: "\u{f15b}" },
  vue: { color: "green", glyph: "\u{e8dc}" },
  wasm: { color: "purple", glyph: "\u{f15b}" },
  wav: { color: "red", glyph: "\u{e638}" },
  webp: { color: "aqua", glyph: "\u{f1c5}" },
  woff: { color: "red", glyph: "\u{f15b}" },
  woff2: { color: "red", glyph: "\u{f15b}" },
  xhtml: { color: "red", glyph: "\u{e736}" },
  xml: { color: "green", glyph: "\u{e619}" },
  xsd: { color: "green", glyph: "\u{e619}" },
  xsl: { color: "green", glyph: "\u{e619}" },
  xslt: { color: "green", glyph: "\u{e619}" },
  yaml: { color: "red", glyph: "\u{e8eb}" },
  yml: { color: "red", glyph: "\u{e8eb}" },
  zig: { color: "yellow", glyph: "\u{f15b}" },
  zip: { color: "yellow", glyph: "\u{e6aa}" },
  zsh: { color: "orange", glyph: "\u{ebca}" },
};

const FILENAME_ICONS: Record<string, IconDef> = {
  ".editorconfig": { color: "blue", glyph: "\u{e615}" },
  ".env": { color: "yellow", glyph: "\u{e615}" },
  ".env.development": { color: "yellow", glyph: "\u{e615}" },
  ".env.example": { color: "yellow", glyph: "\u{e615}" },
  ".env.local": { color: "yellow", glyph: "\u{e615}" },
  ".env.production": { color: "yellow", glyph: "\u{e615}" },
  ".env.test": { color: "yellow", glyph: "\u{e615}" },
  ".gitattributes": { color: "red", glyph: "\u{e702}" },
  ".gitignore": { color: "red", glyph: "\u{e702}" },
  ".gitmodules": { color: "red", glyph: "\u{e702}" },
  ".prettierrc": { color: "blue", glyph: "\u{f15b}" },
  "astro.config.js": { color: "orange", glyph: "\u{e735}" },
  "astro.config.mjs": { color: "orange", glyph: "\u{e735}" },
  "astro.config.ts": { color: "orange", glyph: "\u{e735}" },
  "biome.json": { color: "green", glyph: "\u{f15b}" },
  "biome.jsonc": { color: "green", glyph: "\u{f15b}" },
  "bun.lock": { color: "orange", glyph: "\u{e76f}" },
  "bun.lockb": { color: "orange", glyph: "\u{e76f}" },
  "commitlint.config.mjs": { color: "aqua", glyph: "\u{f15b}" },
  "docker-compose.yaml": { color: "blue", glyph: "\u{e7b0}" },
  "docker-compose.yml": { color: "blue", glyph: "\u{e7b0}" },
  dockerfile: { color: "blue", glyph: "\u{e7b0}" },
  "eslint.config.cjs": { color: "purple", glyph: "\u{e7d2}" },
  "eslint.config.js": { color: "purple", glyph: "\u{e7d2}" },
  "eslint.config.mjs": { color: "purple", glyph: "\u{e7d2}" },
  "eslint.config.ts": { color: "purple", glyph: "\u{e7d2}" },
  "herdr-plugin.toml": { color: "blue", glyph: "\u{e6b2}" },
  "jest.config.cjs": { color: "red", glyph: "\u{e807}" },
  "jest.config.js": { color: "red", glyph: "\u{e807}" },
  "jest.config.ts": { color: "red", glyph: "\u{e807}" },
  license: { color: "gray", glyph: "\u{e60a}" },
  "license.apache-2.0": { color: "gray", glyph: "\u{e60a}" },
  "license.md": { color: "gray", glyph: "\u{e60a}" },
  "license.mit": { color: "gray", glyph: "\u{e60a}" },
  makefile: { color: "red", glyph: "\u{e673}" },
  "netlify.toml": { color: "blue", glyph: "\u{e83c}" },
  "next.config.js": { color: "blue", glyph: "\u{e83e}" },
  "next.config.mjs": { color: "blue", glyph: "\u{e83e}" },
  "next.config.ts": { color: "blue", glyph: "\u{e83e}" },
  "nuxt.config.ts": { color: "green", glyph: "\u{e931}" },
  "package-lock.json": { color: "red", glyph: "\u{e71e}" },
  "package.json": { color: "red", glyph: "\u{e71e}" },
  "pnpm-lock.yaml": { color: "yellow", glyph: "\u{e865}" },
  "pnpm-workspace.yaml": { color: "yellow", glyph: "\u{e865}" },
  "prettier.config.cjs": { color: "blue", glyph: "\u{f15b}" },
  "prettier.config.js": { color: "blue", glyph: "\u{f15b}" },
  "prettier.config.mjs": { color: "blue", glyph: "\u{f15b}" },
  "prettier.config.ts": { color: "blue", glyph: "\u{f15b}" },
  readme: { color: "blue", glyph: "\u{e73e}" },
  "readme.md": { color: "blue", glyph: "\u{e73e}" },
  "tsconfig.json": { color: "blue", glyph: "\u{e69d}" },
  "turbo.json": { color: "yellow", glyph: "\u{f15b}" },
  "vercel.json": { color: "gray", glyph: "\u{e8d3}" },
  "vite.config.js": { color: "orange", glyph: "\u{e8d6}" },
  "vite.config.mts": { color: "orange", glyph: "\u{e8d6}" },
  "vite.config.ts": { color: "orange", glyph: "\u{e8d6}" },
  "vitest.config.mts": { color: "yellow", glyph: "\u{e8d9}" },
  "vitest.config.ts": { color: "yellow", glyph: "\u{e8d9}" },
  "yarn.lock": { color: "blue", glyph: "\u{e8ec}" },
};

const FOLDER_ICONS: Record<string, IconDef> = {
  __mocks__: { color: "aqua", glyph: "\u{ea83}" },
  __snapshots__: { color: "aqua", glyph: "\u{ea83}" },
  __tests__: { color: "aqua", glyph: "\u{ea83}" },
  ".git": { color: "red", glyph: "\u{e702}" },
  ".githooks": { color: "red", glyph: "\u{e702}" },
  ".github": { color: "beige", glyph: "\u{e709}" },
  ".gitlab": { color: "red", glyph: "\u{e7eb}" },
  ".husky": { color: "purple", glyph: "\u{ea83}" },
  ".idea": { color: "purple", glyph: "\u{e7b5}" },
  ".vscode": { color: "blue", glyph: "\u{e8da}" },
  ".vscode-test": { color: "blue", glyph: "\u{e8da}" },
  android: { color: "green", glyph: "\u{e70e}" },
  api: { color: "yellow", glyph: "\u{ea83}" },
  apis: { color: "yellow", glyph: "\u{ea83}" },
  app: { color: "green", glyph: "\u{ea83}" },
  apps: { color: "green", glyph: "\u{ea83}" },
  asset: { color: "yellow", glyph: "\u{ea83}" },
  assets: { color: "yellow", glyph: "\u{ea83}" },
  bin: { color: "red", glyph: "\u{ea83}" },
  build: { color: "red", glyph: "\u{ea83}" },
  cache: { color: "aqua", glyph: "\u{ea83}" },
  code: { color: "green", glyph: "\u{ea83}" },
  component: { color: "green", glyph: "\u{ea83}" },
  components: { color: "green", glyph: "\u{ea83}" },
  config: { color: "blue", glyph: "\u{ea83}" },
  configs: { color: "blue", glyph: "\u{ea83}" },
  configuration: { color: "blue", glyph: "\u{ea83}" },
  containers: { color: "blue", glyph: "\u{ea83}" },
  coverage: { color: "red", glyph: "\u{ea83}" },
  css: { color: "blue", glyph: "\u{ea83}" },
  database: { color: "yellow", glyph: "\u{ea83}" },
  databases: { color: "yellow", glyph: "\u{ea83}" },
  db: { color: "yellow", glyph: "\u{ea83}" },
  debug: { color: "red", glyph: "\u{ea83}" },
  debugging: { color: "red", glyph: "\u{ea83}" },
  dist: { color: "red", glyph: "\u{ea83}" },
  doc: { color: "blue", glyph: "\u{ea83}" },
  docker: { color: "blue", glyph: "\u{ea83}" },
  docs: { color: "blue", glyph: "\u{ea83}" },
  document: { color: "blue", glyph: "\u{ea83}" },
  documentation: { color: "blue", glyph: "\u{ea83}" },
  documents: { color: "blue", glyph: "\u{ea83}" },
  env: { color: "green", glyph: "\u{ea83}" },
  environment: { color: "green", glyph: "\u{ea83}" },
  envs: { color: "green", glyph: "\u{ea83}" },
  font: { color: "red", glyph: "\u{ea83}" },
  fonts: { color: "red", glyph: "\u{ea83}" },
  githooks: { color: "red", glyph: "\u{e702}" },
  helper: { color: "green", glyph: "\u{ea83}" },
  helpers: { color: "green", glyph: "\u{ea83}" },
  herdr: { color: "blue", glyph: "\u{ea83}" },
  hooks: { color: "aqua", glyph: "\u{ea83}" },
  html: { color: "orange", glyph: "\u{ea83}" },
  i18n: { color: "purple", glyph: "\u{ea83}" },
  ico: { color: "aqua", glyph: "\u{ea83}" },
  icon: { color: "aqua", glyph: "\u{ea83}" },
  icons: { color: "aqua", glyph: "\u{ea83}" },
  image: { color: "aqua", glyph: "\u{ea83}" },
  images: { color: "aqua", glyph: "\u{ea83}" },
  img: { color: "aqua", glyph: "\u{ea83}" },
  ios: { color: "red", glyph: "\u{ea83}" },
  js: { color: "yellow", glyph: "\u{ea83}" },
  json: { color: "red", glyph: "\u{ea83}" },
  k8s: { color: "blue", glyph: "\u{ea83}" },
  kubernetes: { color: "blue", glyph: "\u{ea83}" },
  lang: { color: "purple", glyph: "\u{ea83}" },
  language: { color: "purple", glyph: "\u{ea83}" },
  languages: { color: "purple", glyph: "\u{ea83}" },
  lib: { color: "green", glyph: "\u{ea83}" },
  library: { color: "green", glyph: "\u{ea83}" },
  libs: { color: "green", glyph: "\u{ea83}" },
  locale: { color: "purple", glyph: "\u{ea83}" },
  locales: { color: "purple", glyph: "\u{ea83}" },
  markdown: { color: "blue", glyph: "\u{ea83}" },
  md: { color: "blue", glyph: "\u{ea83}" },
  messages: { color: "red", glyph: "\u{ea83}" },
  meta: { color: "green", glyph: "\u{ea83}" },
  migrations: { color: "yellow", glyph: "\u{ea83}" },
  node_modules: { color: "red", glyph: "\u{e71e}" },
  out: { color: "red", glyph: "\u{ea83}" },
  page: { color: "orange", glyph: "\u{ea83}" },
  pages: { color: "orange", glyph: "\u{ea83}" },
  post: { color: "blue", glyph: "\u{ea83}" },
  posts: { color: "blue", glyph: "\u{ea83}" },
  public: { color: "blue", glyph: "\u{ea83}" },
  release: { color: "red", glyph: "\u{ea83}" },
  sass: { color: "purple", glyph: "\u{ea83}" },
  screen: { color: "orange", glyph: "\u{ea83}" },
  screens: { color: "orange", glyph: "\u{ea83}" },
  script: { color: "orange", glyph: "\u{ea83}" },
  scripts: { color: "orange", glyph: "\u{ea83}" },
  scss: { color: "purple", glyph: "\u{ea83}" },
  seeds: { color: "yellow", glyph: "\u{ea83}" },
  server: { color: "blue", glyph: "\u{ea83}" },
  setting: { color: "blue", glyph: "\u{ea83}" },
  settings: { color: "blue", glyph: "\u{ea83}" },
  source: { color: "green", glyph: "\u{ea83}" },
  sources: { color: "green", glyph: "\u{ea83}" },
  spec: { color: "aqua", glyph: "\u{ea83}" },
  specs: { color: "aqua", glyph: "\u{ea83}" },
  src: { color: "green", glyph: "\u{ea83}" },
  static: { color: "blue", glyph: "\u{ea83}" },
  style: { color: "blue", glyph: "\u{ea83}" },
  styles: { color: "blue", glyph: "\u{ea83}" },
  stylesheet: { color: "blue", glyph: "\u{ea83}" },
  stylesheets: { color: "blue", glyph: "\u{ea83}" },
  temp: { color: "aqua", glyph: "\u{ea83}" },
  test: { color: "aqua", glyph: "\u{ea83}" },
  testing: { color: "aqua", glyph: "\u{ea83}" },
  tests: { color: "aqua", glyph: "\u{ea83}" },
  tmp: { color: "aqua", glyph: "\u{ea83}" },
  tool: { color: "red", glyph: "\u{ea83}" },
  tools: { color: "red", glyph: "\u{ea83}" },
  translations: { color: "purple", glyph: "\u{ea83}" },
  type: { color: "blue", glyph: "\u{ea83}" },
  types: { color: "blue", glyph: "\u{ea83}" },
  typings: { color: "blue", glyph: "\u{ea83}" },
  util: { color: "green", glyph: "\u{ea83}" },
  utils: { color: "green", glyph: "\u{ea83}" },
  view: { color: "orange", glyph: "\u{ea83}" },
  views: { color: "orange", glyph: "\u{ea83}" },
  vue: { color: "green", glyph: "\u{ea83}" },
};

const DEFAULT_FILE: IconDef = { color: "gray", glyph: "\u{f15b}" };
const DEFAULT_FOLDER: IconDef = { color: "blue", glyph: "\u{ea83}" };

function lookup(
  path: string,
  byName: Record<string, IconDef>,
  byExt: Record<string, IconDef>,
  fallback: IconDef
): IconDef {
  const basename = path.split("/").pop()?.toLowerCase() ?? "";
  const byNameHit = byName[basename];
  if (byNameHit) {
    return byNameHit;
  }
  const ext = basename.split(".").pop() ?? "";
  return byExt[ext] ?? fallback;
}

export function fileIcon(path: string): string {
  return lookup(path, FILENAME_ICONS, FILE_ICONS, DEFAULT_FILE).glyph;
}

export function fileColor(path: string): IconColorKey {
  return lookup(path, FILENAME_ICONS, FILE_ICONS, DEFAULT_FILE).color;
}

export function folderIcon(path: string): string {
  return lookup(path, FOLDER_ICONS, {}, DEFAULT_FOLDER).glyph;
}

export function folderColor(path: string): IconColorKey {
  return lookup(path, FOLDER_ICONS, {}, DEFAULT_FOLDER).color;
}

export const CHEVRON_DOWN = "\u{eab4}";
export const CHEVRON_RIGHT = "\u{eab6}";

export const GIT_PUSH_ICON = "\u{f431}";
export const GIT_PULL_ICON = "\u{f433}";

export const STATUS_ADDED = "\u{f457}";
export const STATUS_MODIFIED = "\u{f459}";
export const STATUS_RENAMED = "\u{f45a}";
export const STATUS_DELETED = "\u{f458}";
export const STATUS_COPIED = "\u{f4bb}";
export const STATUS_TYPE_CHANGED = "\u{f412}";
export const STATUS_UNTRACKED = "\u{f50c}";
